#!/usr/bin/env python3
"""derive_constraints.py — generate the complete spec-time SDC/SGDC as a pure function of
design.md §1.6 (clocks) + §1.4.1 (Top-Level IO). No LLM overlay.

Usage:  python3 derive_constraints.py <workdir>
Reads:  <workdir>/manifest.json (module = <TOP>) + <workdir>/design.md
Writes: <workdir>/constraints/<TOP>.sdc + <TOP>.sgdc
Prints: {top, clocks, data_ports, resets} JSON on stdout.
Exit:   non-zero + stderr on any table defect (fail-loud; never a thin file).
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

_THIS = Path(__file__).resolve().parent
sys.path.insert(0, str(_THIS))
from check_coverage import extract_section, parse_markdown_table  # noqa: E402
from validate_spec_review import gate_verdict  # noqa: E402  (Task 1 pure fold)

STAGE = "specification"

_IO_DELAY_FRAC = 0.3
_CLK_SEC = r"§?\s*1\.6.*Clocks?\s+and\s+Freq"
_IO_SEC = r"§?\s*1\.4\.1.*Top.Level\s+IO"


def _fail(msg: str):
    sys.exit(f"derive_constraints: {msg}")


def _clocks(design: str) -> list[dict]:
    rows = parse_markdown_table(extract_section(design, _CLK_SEC))
    if not rows:
        _fail("design.md §1.6 Clocks and Frequencies table not found / empty")
    clocks = []
    for r in rows:
        name = r.get("Clock Name", "").strip()
        if not name:
            continue
        try:
            period = float(r.get("SDC Period (ns)", "").strip())
        except ValueError:
            _fail(
                f"clock {name!r}: non-numeric SDC Period {r.get('SDC Period (ns)')!r}"
            )
        clocks.append(
            {
                "name": name,
                "period": period,
                "relationship": r.get("Relationship", "").strip().lower(),
                "generated": r.get("Generated", "no").strip().lower()
                in {"yes", "y", "true"},
            }
        )
    if not clocks:
        _fail("§1.6 has no clock rows")
    return clocks


def _ports(design: str) -> list[dict]:
    rows = parse_markdown_table(extract_section(design, _IO_SEC))
    if not rows:
        _fail("design.md §1.4.1 Top-Level IO table not found / empty")
    ports = []
    for r in rows:
        sig = r.get("Signal", "").strip()
        if not sig:
            continue
        role = r.get("Role", "").strip().lower()
        if role not in {"clock", "reset", "data"}:
            _fail(f"port {sig!r}: missing/invalid Role {role!r} (clock/reset/data)")
        ports.append(
            {
                "signal": sig,
                "direction": r.get("Direction", "").strip().lower(),
                "domain": r.get("Clock Domain", "").strip(),
                "role": role,
                "reset_polarity": r.get("ResetPolarity", "").strip(),
                "reset_kind": r.get("ResetKind", "").strip().lower(),
            }
        )
    return ports


def generate_sdc(top: str, clocks: list[dict], ports: list[dict]) -> str:
    out = [
        f"# SDC constraints for {top}",
        "# Generated by derive_constraints.py from design.md §1.6 + §1.4.1 — do not hand-edit.",
        f"# Note: clock periods MUST match {top}.sgdc.",
        "",
    ]
    non_gen = [c for c in clocks if not c["generated"]]
    for c in clocks:
        if c["generated"]:
            out.append(
                f"# create_generated_clock {c['name']}: deferred to RTL (clock-gen pin not yet known)"
            )
            continue
        out.append(
            f"create_clock -name {c['name']} -period {c['period']} [get_ports {c['name']}]"
        )
    async_names = [c["name"] for c in non_gen if c["relationship"] == "async"]
    if async_names and len(non_gen) >= 2:
        groups = []
        sync_grp = [c["name"] for c in non_gen if c["relationship"] != "async"]
        if sync_grp:
            groups.append("-group [get_clocks {" + " ".join(sync_grp) + "}]")
        groups.extend(f"-group [get_clocks {a}]" for a in async_names)
        out.append("set_clock_groups -asynchronous " + " ".join(groups))
    out.append("")
    out.append(
        "set_clock_uncertainty -setup 0.2 [all_clocks]   ;# placeholder; replace per process library"
    )
    out.append(
        "set_clock_uncertainty -hold  0.0 [all_clocks]   ;# pre-CTS hold = 0; replace per CTS skew"
    )
    out.append("")
    period_of = {c["name"]: c["period"] for c in non_gen}
    for p in ports:
        if p["role"] != "data":
            continue
        T = period_of.get(p["domain"])
        if T is None:
            continue  # domain is a generated clock (deferred) or absent (R-F-gated); defensive
        delay = round(T * _IO_DELAY_FRAC, 4)
        if p["direction"] == "input":
            out.append(
                f"set_input_delay  {delay} -clock {p['domain']} [get_ports {{{p['signal']}}}]"
            )
        elif p["direction"] == "output":
            out.append(
                f"set_output_delay {delay} -clock {p['domain']} [get_ports {{{p['signal']}}}]"
            )
    return "\n".join(out) + "\n"


def generate_sgdc(top: str, clocks: list[dict], ports: list[dict]) -> str:
    out = [
        f"# SGDC constraints for {top}",
        "# Generated by derive_constraints.py — do not hand-edit.",
        f"# Note: clock periods MUST match {top}.sdc.",
        "",
        f"current_design {top}",
        "",
    ]
    for c in clocks:
        if c["generated"]:
            continue
        half = round(c["period"] / 2, 4)
        out.append(f"clock -name {c['name']} -period {c['period']} -edge {{0 {half}}}")
    out.append("")
    for p in ports:
        if p["role"] != "reset":
            continue
        async_flag = " -async" if p["reset_kind"] == "async" else ""
        out.append(
            f"reset -name {p['signal']} -value {p['reset_polarity']}{async_flag}"
        )
        out.append(
            f"abstract_port -ports {p['signal']} -clock {p['domain']} -reset {p['signal']}"
        )
    if any(p["role"] == "reset" for p in ports):
        out.append("")
    clock_names = {c["name"] for c in clocks if not c["generated"]}
    by_domain: dict[str, list[str]] = {}
    for p in ports:
        if p["role"] == "data":
            if p["domain"] not in clock_names:
                continue  # domain is a generated clock (deferred) or absent; defensive (mirrors generate_sdc)
            by_domain.setdefault(p["domain"], []).append(p["signal"])
    for dom, sigs in by_domain.items():
        out.append(f"abstract_port -ports {{{' '.join(sigs)}}} -clock {dom}")
    return "\n".join(out) + "\n"


def _data_port_in_sgdc(signal: str, sgdc: str) -> bool:
    """True iff `signal` appears as a token inside a data `abstract_port -ports {...}` group."""
    for line in sgdc.splitlines():
        if line.startswith("abstract_port -ports {"):
            group = line.split("{", 1)[1].split("}", 1)[0]
            if signal in group.split():
                return True
    return False


def _self_check(top: str, clocks: list[dict], ports: list[dict], sdc: str, sgdc: str):
    if f"current_design {top}" not in sgdc:
        _fail(f"self-check: SGDC missing 'current_design {top}'")
    for c in clocks:
        if c["generated"]:
            continue
        if f"create_clock -name {c['name']} " not in sdc:
            _fail(f"self-check: no create_clock for clock {c['name']!r}")
    # A data port whose Clock Domain is a *generated* clock is deferred to RTL
    # (create_generated_clock pin not yet known); generate_sdc/generate_sgdc skip it
    # by design (see their "domain is a generated clock (deferred); defensive"
    # branches), so the self-check must mirror that skip — not demand an abstract_port
    # the generators intentionally did not emit. Only non-generated-clock data ports
    # are required to carry one.
    non_generated = {c["name"] for c in clocks if not c["generated"]}
    for p in ports:
        if (
            p["role"] == "data"
            and p["domain"] in non_generated
            and not _data_port_in_sgdc(p["signal"], sgdc)
        ):
            _fail(f"self-check: no abstract_port for data port {p['signal']!r}")
        if p["role"] == "reset":
            if p["reset_polarity"] not in {"0", "1"}:
                _fail(
                    f"reset {p['signal']!r}: ResetPolarity must be 0 or 1 (got {p['reset_polarity']!r})"
                )
            if p["reset_kind"] not in {"sync", "async"}:
                _fail(
                    f"reset {p['signal']!r}: ResetKind must be sync or async (got {p['reset_kind']!r})"
                )


def derive_constraints(workdir: Path) -> dict:
    manifest = json.loads((workdir / "manifest.json").read_text(encoding="utf-8"))
    top = manifest.get(
        "module"
    )  # <TOP> pinned to manifest.module (== finalize top_module)
    if not top:
        _fail("manifest.json missing 'module' (the <TOP> name)")
    design = (workdir / "design.md").read_text(encoding="utf-8")
    clocks = _clocks(design)
    ports = _ports(design)
    sdc = generate_sdc(top, clocks, ports)
    sgdc = generate_sgdc(top, clocks, ports)
    _self_check(top, clocks, ports, sdc, sgdc)
    cdir = workdir / "constraints"
    cdir.mkdir(exist_ok=True)
    (cdir / f"{top}.sdc").write_text(sdc, encoding="utf-8")
    (cdir / f"{top}.sgdc").write_text(sgdc, encoding="utf-8")
    return {
        "top": top,
        "clocks": len(clocks),
        "data_ports": sum(1 for p in ports if p["role"] == "data"),
        "resets": sum(1 for p in ports if p["role"] == "reset"),
    }


def _now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _envelope(module, *, status, stage_specific, artifacts) -> dict:
    return {
        "schema_version": 1,
        "stage": STAGE,
        "module": module,
        "produced_at": _now_iso(),
        "status": status,
        "artifacts": artifacts,
        "stage_specific": stage_specific,
    }


def _write_result(workdir: Path, env: dict) -> None:
    (workdir / "result.json").write_text(json.dumps(env, indent=2) + "\n")
    sys.stdout.write(
        f"[derive_constraints] Written: {workdir / 'result.json'} (status={env['status']})\n"
    )


def compute_spec_gate(workdir: Path, waived: list) -> dict:
    """Re-derive the Step-7 gate verdict in-process from the on-disk spec-review.json
    (already schema-gated when Step 7 wrote it -> call the pure fold, not the CLI),
    then merge the human waiver classification relayed via --waived."""
    doc = json.loads((Path(workdir) / "spec-review.json").read_text(encoding="utf-8"))
    g = gate_verdict(doc)
    g["waived"] = waived
    return g


def enumerate_artifacts(workdir: Path, top: str) -> list[dict]:
    """Fixed specification artifact set, present-only, with kinds. NEVER lists brainstorm.md
    (module-root, outside the workdir — would break promote()) or result.json (self)."""
    workdir = Path(workdir)
    manifest = json.loads((workdir / "manifest.json").read_text(encoding="utf-8"))
    fixed = [
        ("design.md", "design"),
        ("manifest.json", "manifest"),
        ("coverage.json", "coverage"),
        ("spec-review.json", "spec-review"),
        (f"constraints/{top}.sdc", "sdc"),
        (f"constraints/{top}.sgdc", "sgdc"),
    ]
    child_docs = [
        (c["doc"], "child-design") for c in manifest.get("children", []) if c.get("doc")
    ]
    return [
        {"path": p, "kind": k} for p, k in fixed + child_docs if (workdir / p).is_file()
    ]


def build_result(workdir, module, ppa_targets, waived, status) -> int:
    """Assemble the lean specification result.json. Re-runs derive_constraints() in-process
    (so <TOP> + the constraint files cannot diverge), re-derives spec_gate from the on-disk
    spec-review.json, enforces the approve precondition, enumerates artifacts[], writes the
    envelope. Returns 0 (result.json written, pass or fail). A raise -> main() exit 2 (BLOCKED).

    Agent γ-floor inputs (correction A): ppa_targets (D6 brainstorm), waived (the human waiver
    classification recorded at the Step-8 gate), status (the user's approve/reject). The gate
    verdict itself is re-derived, NOT agent-supplied."""
    workdir = Path(workdir)
    info = derive_constraints(
        workdir
    )  # reuse: resolves <TOP> + regenerates SDC/SGDC + self-checks
    top = info["top"]  # == manifest.module (the single <TOP> source)

    spec_gate = compute_spec_gate(workdir, waived)
    # Owner-decided granularity: waiver pairing keys on (child, lens) and ignores location,
    # matching the SKILL's own gate granularity (SKILL.md:269) — intentional, not a defect.
    waived_keys = {(w.get("child"), w.get("lens")) for w in waived}
    unresolved = [
        f
        for f in spec_gate["flagged"]
        if (f.get("child"), f.get("lens")) not in waived_keys
    ]

    # Approve precondition (SKILL.md:269): a pass is honored only when the gate is clear OR
    # every flagged finding is waived. Never ship an unreviewed/unwaived pass.
    if status == "pass" and unresolved:
        ss = {
            "top_module": top,
            "fail_reason": "approve precondition unmet: flagged spec-review findings neither cleared nor waived",
            "spec_gate": spec_gate,
        }
        _write_result(
            workdir,
            _envelope(
                module,
                status="fail",
                stage_specific=ss,
                artifacts=enumerate_artifacts(workdir, top),
            ),
        )
        return 0

    if status == "pass":
        ss = {"top_module": top, "ppa_targets": ppa_targets, "spec_gate": spec_gate}
    else:
        ss = {
            "top_module": top,
            "fail_reason": "design.md gate rejected at human review",
            "spec_gate": spec_gate,
        }
    _write_result(
        workdir,
        _envelope(
            module,
            status=status,
            stage_specific=ss,
            artifacts=enumerate_artifacts(workdir, top),
        ),
    )
    return 0


def main(argv: list[str]) -> int:
    if len(argv) > 1 and argv[1] == "finalize":
        ap = argparse.ArgumentParser(
            prog="derive_constraints.py finalize",
            description="Assemble the lean specification result.json from the workdir.",
        )
        ap.add_argument("--workdir", required=True, type=Path)
        ap.add_argument("--module", required=True)
        ap.add_argument(
            "--ppa-targets",
            default="[]",
            help="ppa_targets JSON array, verbatim from D6 brainstorm (γ-floor)",
        )
        ap.add_argument(
            "--waived",
            default="[]",
            help="human-waiver JSON array recorded at the Step-8 gate (γ-floor)",
        )
        ap.add_argument(
            "--status",
            required=True,
            choices=["pass", "fail"],
            help="the human approve/reject decision at the Step-8 design.md gate (γ-floor)",
        )
        try:
            a = ap.parse_args(argv[2:])
        except SystemExit as exc:
            if exc.code not in (0, None):
                print("[derive_constraints] ERROR: usage", file=sys.stderr)
                return 2
            return 0
        try:
            ppa = json.loads(a.ppa_targets)
            waived = json.loads(a.waived)
        except json.JSONDecodeError as exc:
            print(
                f"[derive_constraints] ERROR: --ppa-targets/--waived not valid JSON: {exc}",
                file=sys.stderr,
            )
            return 2
        try:
            return build_result(a.workdir, a.module, ppa, waived, a.status)
        except Exception as exc:  # noqa: BLE001 — any failure to operate is BLOCKED
            print(f"[derive_constraints] FAIL=internal {exc}", file=sys.stderr)
            return 2
    # ── legacy positional CLI (UNCHANGED behavior): derive_constraints.py <workdir> ──
    print(json.dumps(derive_constraints(Path(argv[1])), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
