#!/usr/bin/env python3
"""Aggregate the ledger's files[] + incdirs[] into filelist.txt.

Format: '#'-only comments, one '+incdir+<dir>' per incdir, one file per line, paths
verbatim from children (relative to workdir). '//' comments are forbidden (SpyGlass
does not recognize them). Order is stable (children sorted; first-seen within a child).

Usage: build_filelist.py --ledger <.child_reports.json> --out <workdir/filelist.txt>
Exit: non-zero + stderr on malformed ledger (fail-loud; no output written).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_THIS = Path(__file__).resolve().parent
sys.path.insert(0, str(_THIS))
from ledger_io import LedgerError, load_ledger  # noqa: E402


def render(ledger: dict) -> str:
    incdirs, files, seen_i, seen_f = [], [], set(), set()
    for name in sorted(ledger):
        rec = ledger[name]
        for d in rec.get("incdirs", []):
            if d not in seen_i:
                seen_i.add(d)
                incdirs.append(d)
        for f in rec["files"]:
            if f not in seen_f:
                seen_f.add(f)
                files.append(f)
    out = [
        "# rtl-design filelist — generated by build_filelist.py; do not hand-edit.",
        "# Use '#' comments only (SpyGlass does not recognize double-slash comments).",
    ]
    out += [f"+incdir+{d}" for d in incdirs]
    out += files
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ledger", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    a = ap.parse_args()
    try:
        ledger = load_ledger(a.ledger)
    except LedgerError as e:
        print(f"build_filelist: {e}", file=sys.stderr)
        return 1
    a.out.write_text(render(ledger), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
