#!/usr/bin/env python3
"""spec seed — carry prior canonical specification PRODUCTS into a rework/freeze workdir.

Whitelist copy with NO-CLOBBER semantics (a file already present is never overwritten —
resume-idempotent): design.md + the per-child <child>.md set (root *.md), manifest.json,
coverage.json / ppa.json, and the constraint files. coverage.json / ppa.json are
regenerated by check-coverage / a passing finalize, but MUST still be carried: a rework
finalized as status=fail promotes a present-only artifact set, and an absent ppa.json
would be GC'd out of canonical — severing synthesis/power-analysis's declared input.
Adjudication artifacts are excluded by construction (room-birth hygiene, ARCHITECTURE
§7.2): result.json is never seeded (a carried-in stale envelope is reaped
blocked/stale_result). The judged review record (spec-review.json) is copied ONLY
with --freeze — the freeze branch's byte-carry that keeps a `pin` on the record alive.
First-run (no canonical dir) is a no-op. Canonical defaults to `{workdir}/../..`
(workdir is runs/<N>).
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

PRODUCTS = (
    "*.md",
    "manifest.json",
    "coverage.json",
    "ppa.json",
    "constraints/*.sdc",
    "constraints/*.sgdc",
)
FREEZE_EXTRAS = ("spec-review.json",)


def seed(canonical: Path, workdir: Path, freeze: bool = False) -> list:
    copied: list = []
    if not canonical.is_dir():
        return copied
    for g in PRODUCTS + (FREEZE_EXTRAS if freeze else ()):
        for src in sorted(canonical.glob(g)):
            if not src.is_file():
                continue
            rel = src.relative_to(canonical)
            dst = workdir / rel
            if dst.exists():  # no-clobber: keep freshly-authored work
                continue
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied.append(str(rel))
    return copied


def run(workdir, canonical=None, freeze: bool = False) -> int:
    workdir = Path(workdir)
    canonical = (
        Path(canonical) if canonical is not None else workdir.resolve().parent.parent
    )
    copied = seed(canonical, workdir, freeze=freeze)
    print(json.dumps({"seeded": copied, "count": len(copied)}, ensure_ascii=False))
    return 0
