#!/usr/bin/env python3
"""rtl assemble — build the ledger + filelist + README, then run the post exit-gate.

Collapses the four finalize-flow steps the SKILL.md flow always chained (ledger
build + filelist render + README render + the post exit-gate) into one idempotent
verb. The 4.3 conformance loop re-runs `assemble --seeded` every round, so this is
safe to re-call.

stdout/exit contract:
  * BUILD ERROR (malformed/contract-violating reports or ledger): exit 1, message on
    STDERR, and NO stdout verdict — the main thread reads stderr as the fail_reason.
  * otherwise: write ledger/filelist/README, then print the post-gate verdict JSON on
    STDOUT; exit code = truth (0 pass / 1 fail). The presence of a stdout verdict is
    how the main thread tells a gate fail apart from a build error.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from rtl._ledger import LedgerError, load_ledger, merge_filter
from rtl.partition import post_verdict


class _BuildError(Exception):
    """A reports/ledger contract violation — fail loud, never emit degraded output."""


def _read_json(p: Path):
    return json.loads(p.read_text(encoding="utf-8"))


def merge_ledger(fresh: Path, manifest: Path, out: Path, seeded: Path | None) -> dict:
    """Merge fresh done-child reports onto any seeded prior ledger, keep only the manifest
    roster, shape-validate, write `out`, and return the ledger. Raises _BuildError /
    LedgerError on any contract violation (fail-loud)."""
    fresh_raw = _read_json(fresh)
    merged_fresh = {}
    for name, rec in fresh_raw.items():
        if rec.get("status") != "done":
            continue
        # A done child MUST carry its required contract fields; a missing 'files' would
        # otherwise be silently defaulted, dropping that child's RTL from the filelist
        # (Iron Rule #1). Fail loud on the contract violation instead.
        for req in ("files", "annotations"):
            if req not in rec:
                raise _BuildError(f"done child {name!r} missing required {req!r}")
        entry = {"files": rec["files"], "annotations": rec["annotations"]}
        if "incdirs" in rec:
            entry["incdirs"] = rec["incdirs"]
        merged_fresh[name] = entry

    seeded_ledger = load_ledger(seeded) if (seeded and seeded.is_file()) else {}
    roster = [c["name"] for c in _read_json(manifest).get("children", [])]
    ledger = merge_filter(seeded_ledger, merged_fresh, roster)

    out.write_text(
        json.dumps(ledger, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    load_ledger(out)  # fail-loud: never leave a malformed ledger on disk silently
    return ledger


def render_filelist(ledger: dict) -> str:
    incdirs, files, seen_i, seen_f = [], [], set(), set()
    for name in sorted(ledger):
        rec = ledger[name]
        for d in rec.get("incdirs", []):
            if d not in seen_i:
                seen_i.add(d)
                incdirs.append(d)
        for f in rec["files"]:
            if f not in seen_f:
                seen_f.add(f)
                files.append(f)
    out = [
        "# rtl-design filelist — generated by the rtl assemble verb; do not hand-edit.",
        "# Use '#' comments only (SpyGlass does not recognize double-slash comments).",
    ]
    out += [f"+incdir+{d}" for d in incdirs]
    out += files
    return "\n".join(out) + "\n"


def _agg(ledger: dict, family: str, key: str) -> list:
    items: list = []
    for name in sorted(ledger):
        items.extend(ledger[name]["annotations"].get(family, {}).get(key, []))
    return items


def render_readme(ledger: dict) -> str:
    sync = _agg(ledger, "sgdc", "sync_cell")
    rsync = _agg(ledger, "sgdc", "reset_synchronizer")
    sca = _agg(ledger, "sgdc", "set_case_analysis")
    qs = _agg(ledger, "sgdc", "quasi_static")
    gc = _agg(ledger, "sdc", "create_generated_clock")
    mcp = _agg(ledger, "sdc", "set_multicycle_path")
    fp = _agg(ledger, "sdc", "set_false_path")

    lines = [
        "## Constraint-annotation note",
        "",
        "### SGDC",
        "",
    ]
    if not (sync or rsync or sca or qs):
        lines.append("single clock domain; no deep annotations needed.")
    else:
        lines += [f"- sync_cell -name {m}" for m in sync]
        lines += [f"- reset_synchronizer -name {m}" for m in rsync]
        lines += [f"- set_case_analysis {e['value']} {e['port']}" for e in sca]
        lines += [f"- quasi_static -name {s}" for s in qs]

    lines += ["", "### SDC", ""]
    gc_str = "; ".join(f"{g['module']}.{g['pin']}" for g in gc) if gc else "none"
    lines.append(f"- create_generated_clock: {gc_str}")
    lines.append(f"- set_multicycle_path: {'; '.join(mcp) if mcp else 'none'}")
    lines.append(f"- set_false_path: {'; '.join(fp) if fp else 'none'}")
    return "\n".join(lines) + "\n"


def run(workdir, manifest, top, *, seeded=False) -> int:
    workdir, manifest = Path(workdir), Path(manifest)
    fresh = workdir / "fresh_reports.json"
    out = workdir / ".child_reports.json"
    seeded_path = out if seeded else None
    try:
        ledger = merge_ledger(fresh, manifest, out, seeded_path)
    except (_BuildError, LedgerError, json.JSONDecodeError, OSError, KeyError) as e:
        print(f"[rtl assemble] {e}", file=sys.stderr)
        return 1
    (workdir / "filelist.txt").write_text(render_filelist(ledger), encoding="utf-8")
    (workdir / "README.md").write_text(render_readme(ledger), encoding="utf-8")
    verdict, rc = post_verdict(manifest, top, fresh, out)
    print(json.dumps(verdict, ensure_ascii=False))
    return rc
