#!/usr/bin/env python3
"""synthesis bootstrap — deploy the synthesis templates into a run workdir.

Behavior-preserving deploy built from focused, unit-testable steps (campaign design
§3.3): shutil.copytree + str.replace do the `cp -a` + `sed -i` work. Upstream
locations (rtl-design, specification SDC/PPA) come from the injected
`<workdir>/inputs.json` — bootstrap re-anchors rtl_load.tcl / dc_run.tcl to the
ABSOLUTE producer stage root; no relpath, no self-navigation.

Deploys templates/ into the caller-provided workdir
(asic/<module>/Design/synthesis/runs/<N>/), substitutes the MY_TOP / MY_RTL_DIR
placeholders, regenerates scripts/rtl_load.tcl from the rtl-design filelist, and
writes scripts/config.tcl. Fail-closed on a missing/empty filelist or an
un-inferrable top. Idempotency guard: aborts when the workdir is already deployed.

Exit codes (returned as int; __main__ does sys.exit):
  0  deployed
  1  fail-closed guard (cannot read top / already deployed / missing or empty
     filelist / missing template dir)
  (2 = usage is owned by argparse in __main__.py)
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path

# This file: skills/synthesis/scripts/synthesis/bootstrap.py
#   parents[2] = skills/synthesis   (-> templates/, ships with the skill)
# The design tree (asic/<module>/...) is anchored on the CWD, NOT on where this code
# lives — matching kernel.py and the stage-subagent contract ("workdir is relative to
# the working tree root containing asic/").
_HERE = Path(__file__).resolve()
_TEMPLATE_DIR = _HERE.parents[2] / "templates"

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _err(msg: str) -> None:
    print(f"[synthesis bootstrap] {msg}", file=sys.stderr)


def top_from_manifest(manifest_dir: Path) -> str | None:
    """TOP from the injected manifest's `module`. The specification stage authors it and
    every other copy — the two result.json echoes, the scaffold's `top` — derives from it.
    `manifest` is a declared input, so a rename invalidates this stage's proof."""
    f = Path(manifest_dir) / "manifest.json"
    if not f.is_file():
        return None
    try:
        top = json.loads(f.read_text(encoding="utf-8")).get("module")
    except json.JSONDecodeError:
        return None
    return top if isinstance(top, str) and _IDENT_RE.match(top) else None


def _is_rtl_entry(line: str) -> bool:
    """True for a real RTL path line in filelist.txt — not a comment (# or //),
    blank, or +/- directive. (rtl_load skip set is {#, //, blank, +/-}.)"""
    if re.match(r"^\s*#", line):
        return False
    if re.match(r"^\s*//", line):
        return False
    if not line.strip():
        return False
    if re.match(r"^\s*[+\-]", line):
        return False
    return True


def _sub(path: Path, placeholder: str, value: str) -> None:
    """In-place placeholder substitution (str.replace — no sed-delimiter hazard)."""
    path.write_text(path.read_text().replace(placeholder, value))


def _write_rtl_load_tcl(dest: Path, rtl_dir: Path) -> int:
    """Regenerate scripts/rtl_load.tcl from filelist.txt (overwrites the template
    placeholder copied by copytree). Fail-closed (return 1) on missing/empty filelist."""
    out = dest / "scripts" / "rtl_load.tcl"
    fl = rtl_dir / "filelist.txt"
    if not fl.is_file():
        _err(f"missing {fl}")
        _err(
            "  Populate Design/rtl-design/filelist.txt with .v / .sv paths in "
            "dependency order."
        )
        return 1
    lines = fl.read_text(errors="replace").splitlines()
    rtl_entries = [ln.replace("\r", "") for ln in lines if _is_rtl_entry(ln)]
    if not rtl_entries:
        _err(f"{fl} has no usable RTL entries (only comments / directives)")
        _err(
            "  Populate Design/rtl-design/filelist.txt with .v / .sv paths in "
            "dependency order."
        )
        return 1
    incdirs: list[str] = []
    for raw in lines:
        m = re.match(r"^\s*\+incdir\+(.+)$", raw.replace("\r", ""))
        if m:
            incdirs.append(f"{rtl_dir}/{m.group(1)}")
    body = [
        "# Generated by synthesis bootstrap from Design/rtl-design/filelist.txt — hand-edit OK",
        "#",
        "# analyze returns 0 on failure. An UNCHECKED failure is not benign: DC keeps going,",
        "# the module ends up unresolved, and (because DC classifies an unresolved reference as",
        "# a Warning, not an Error) dc_run.tcl's check_design gate does not fire either — so a",
        "# design missing a whole module synthesizes and reports a smaller-but-passing QoR.",
        "# Every file is therefore gated; dc_run.tcl gates elaborate/link for the same reason.",
        "proc _analyze_or_die {f} {",
        "    if {![analyze -format sverilog -define SYNTHESIS [list $f]]} {",
        '        puts stderr "ERROR: analyze failed: $f"',
        "        exit 1",
        "    }",
        "}",
    ]
    if incdirs:
        body.append(
            "set_app_var search_path [concat [get_app_var search_path] "
            f"[list {' '.join(incdirs)}]]"
        )
    for entry in rtl_entries:
        body.append(f"_analyze_or_die {{{rtl_dir}/{entry}}}")
    out.write_text("\n".join(body) + "\n")
    return 0


def _write_config_tcl(dest: Path, top: str) -> None:
    """Generate scripts/config.tcl (dc_shell does not inherit shell env vars).
    LIB_DB falls back to the FILL_IN placeholder when unset/empty (shell `${LIB_DB:-}`)."""
    lib_db = os.environ.get("LIB_DB") or "FILL_IN_LIB_DB_PATH"
    (dest / "scripts" / "config.tcl").write_text(
        "# Auto-generated by synthesis bootstrap — dc_shell / pt_shell configuration.\n"
        "# dc_shell does not inherit shell env vars; this file is the sole entry point\n"
        "# for TOP and LIB_DB. Editing LIB_DB here does not require a re-bootstrap.\n"
        f'set ::env(TOP)    "{top}"\n'
        f'set ::env(LIB_DB) "{lib_db}"\n'
    )
    if lib_db == "FILL_IN_LIB_DB_PATH":
        print(
            "[synthesis bootstrap] wrote scripts/config.tcl "
            "(fill in LIB_DB path before make synthesis)"
        )
    else:
        print(f"[synthesis bootstrap] wrote scripts/config.tcl (LIB_DB={lib_db})")


def run(workdir, top: str | None = None) -> int:
    if not _TEMPLATE_DIR.is_dir():
        _err(f"missing template directory: {_TEMPLATE_DIR}")
        return 1

    # The design tree is the CWD (kernel.py + stage-subagent contract). Resolve a
    # relative workdir against it + drop trailing slash.
    tree_root = Path.cwd()
    dest = Path(workdir)
    if not dest.is_absolute():
        dest = tree_root / dest
    dest = Path(str(dest).rstrip("/"))  # consistent path resolution

    inputs = json.loads((dest / "inputs.json").read_text(encoding="utf-8"))
    rtl_dir = Path(inputs["rtl"])

    if not top:
        top = top_from_manifest(inputs["manifest"])
    if not top:
        _err("cannot read top-module name; pass --top <name>")
        _err("  Design/specification/manifest.json must carry a 'module' name.")
        return 1

    dest.mkdir(parents=True, exist_ok=True)
    # A caller may pre-create the workdir with hint files (directive.md
    # etc.); only treat it as already-deployed when Makefile is present.
    if (dest / "Makefile").is_file():
        _err(f"already deployed (detected {dest / 'Makefile'})")
        _err(
            f"  To redeploy, back up and remove {dest}/"
            "{Makefile,constraints.sdc,scripts/} first."
        )
        return 1

    shutil.copytree(_TEMPLATE_DIR, dest, dirs_exist_ok=True)

    # SDC source-of-truth: reuse the spec-stage SDC verbatim when present (already
    # bound to this top — no MY_TOP sub). env.sh is substituted in both branches.
    env_sh = dest / "env.sh"
    user_sdc = Path(inputs["sdc"]) / "constraints" / f"{top}.sdc"
    if user_sdc.is_file():
        shutil.copyfile(user_sdc, dest / "constraints.sdc")
        print(
            f"[synthesis bootstrap] using "
            f"Design/specification/constraints/{top}.sdc -> constraints.sdc"
        )
        _sub(env_sh, "MY_TOP", top)
    else:
        _sub(env_sh, "MY_TOP", top)
        _sub(dest / "constraints.sdc", "MY_TOP", top)
        print(
            "[synthesis bootstrap] no spec SDC; deployed PLACEHOLDER constraints.sdc "
            "(clk=10ns, ports clk/rst_n) — fill it per design.md §1.4 in Step 4."
        )

    _sub(dest / "scripts" / "dc_run.tcl", "MY_RTL_DIR", str(rtl_dir))

    rc = _write_rtl_load_tcl(dest, rtl_dir)
    if rc != 0:
        return rc

    _write_config_tcl(dest, top)

    print(f"\n[synthesis bootstrap] deployed {dest}")
    print(f"  TOP={top}")
    print(f"  RTL_DIR={rtl_dir}")
    return 0
