#!/usr/bin/env python3
"""synthesis bootstrap — deploy the synthesis templates into a run workdir.

Upstream locations (rtl-design, the specification SDC) come from the injected
`<workdir>/dispatch.json` — bootstrap re-anchors rtl_load.tcl / dc_run.tcl to the
ABSOLUTE producer stage root; no relpath, no self-navigation.

Deploys templates/ into the caller-provided workdir
(asic/<module>/Design/synthesis/runs/<N>/), substitutes the MY_TOP / MY_RTL_DIR
placeholders, writes scripts/rtl_load.tcl from the rtl-design filelist, and
writes scripts/config.tcl. Every guard that can fail runs BEFORE the copytree, so a
fail-closed leaves no Makefile for the already-deployed guard to block the retry on.
Idempotency guard: aborts when the workdir is already deployed.

Exit codes (returned as int; __main__ does sys.exit):
  0  deployed
  1  fail-closed guard (cannot read top / already deployed / missing or empty
     filelist / missing template dir)
  (2 = usage is owned by argparse in __main__.py)
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path

# This file: skills/synthesis/scripts/synthesis/bootstrap.py
#   parents[2] = skills/synthesis   (-> templates/, ships with the skill)
# The design tree (asic/<module>/...) is anchored on the CWD, NOT on where this code
# lives — matching kernel.py and the stage-subagent contract ("workdir is relative to
# the working tree root containing asic/").
_HERE = Path(__file__).resolve()
_TEMPLATE_DIR = _HERE.parents[2] / "templates"

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _err(msg: str) -> None:
    print(f"[synthesis bootstrap] {msg}", file=sys.stderr)


def top_from_manifest(manifest_dir: Path) -> str | None:
    """TOP from the injected manifest's `module` — the name the specification stage
    authored, which every other copy in the tree derives from."""
    f = Path(manifest_dir) / "manifest.json"
    if not f.is_file():
        return None
    try:
        top = json.loads(f.read_text(encoding="utf-8")).get("module")
    except json.JSONDecodeError:
        return None
    return top if isinstance(top, str) and _IDENT_RE.match(top) else None


def _load_rtl_files(rtl_dir: Path) -> dict | None:
    """rtl-files.json from the injected rtl-design stage root.

    Not validated here: rtl-design schema-validates it when it writes it, and a stage does
    not reach into another skill's references/ (skills stay decoupled).
    """
    try:
        return json.loads((rtl_dir / "rtl-files.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _sub(path: Path, placeholder: str, value: str) -> None:
    """In-place placeholder substitution (str.replace — no sed-delimiter hazard)."""
    path.write_text(path.read_text().replace(placeholder, value))


def _render_rtl_load_tcl(rtl_dir: Path) -> str | None:
    """scripts/rtl_load.tcl rendered from rtl-files.json, or None when that layout
    yields no RTL (stderr names which). Rendered BEFORE the deploy for the same reason
    the SDC lookup happens there: returning after copytree would leave the Makefile
    that the already-deployed guard then refuses to redeploy over.

    Children are emitted in name order and files in their declared order within a child.
    """
    rtl_files = _load_rtl_files(rtl_dir)
    if rtl_files is None:
        _err(f"missing or unreadable {rtl_dir / 'rtl-files.json'}")
        _err("  rtl-design writes it from its children's reports; re-run that stage.")
        return None
    rtl_entries: list[str] = []
    incdirs: list[str] = []
    for name in sorted(rtl_files):
        rec = rtl_files[name]
        for d in rec.get("incdirs") or []:
            entry = f"{rtl_dir}/{d}"
            if entry not in incdirs:
                incdirs.append(entry)
        for f in rec.get("files") or []:
            if f not in rtl_entries:
                rtl_entries.append(f)
    if not rtl_entries:
        _err(f"{rtl_dir / 'rtl-files.json'} lists no RTL files")
        _err("  rtl-design writes it from its children's reports; re-run that stage.")
        return None
    body = [
        "# Generated by synthesis bootstrap from Design/rtl-design/rtl-files.json — hand-edit OK",
        "#",
        "# analyze returns 0 on failure. An UNCHECKED failure is not benign: DC keeps going,",
        "# the module ends up unresolved, and (because DC classifies an unresolved reference as",
        "# a Warning, not an Error) dc_run.tcl's check_design gate does not fire either — so a",
        "# design missing a whole module synthesizes and reports a smaller-but-passing QoR.",
        "# Every file is therefore gated; dc_run.tcl gates elaborate/link for the same reason.",
        "proc _analyze_or_die {f} {",
        "    if {![analyze -format sverilog -define SYNTHESIS [list $f]]} {",
        '        puts stderr "ERROR: analyze failed: $f"',
        "        exit 1",
        "    }",
        "}",
    ]
    if incdirs:
        body.append(
            "set_app_var search_path [concat [get_app_var search_path] "
            f"[list {' '.join(incdirs)}]]"
        )
    for entry in rtl_entries:
        body.append(f"_analyze_or_die {{{rtl_dir}/{entry}}}")
    return "\n".join(body) + "\n"


def _write_config_tcl(dest: Path, top: str) -> None:
    """Generate scripts/config.tcl: the TOP/LIB_DB source for a dc_shell invoked outside
    the Makefile, which otherwise sources env.sh and exports both.

    LIB_DB is written as a conditional so it can never override one already in the
    environment. An unconditional set does: the placeholder written here when bootstrap ran
    before LIB_DB was exported wins over the real path exported afterwards, and dc_run.tcl
    then dies on `FILL_IN_LIB_DB_PATH` — a file the caller never named."""
    lib_db = os.environ.get("LIB_DB") or "FILL_IN_LIB_DB_PATH"
    (dest / "scripts" / "config.tcl").write_text(
        "# Auto-generated by synthesis bootstrap — dc_shell / pt_shell configuration.\n"
        "# Fallback only: `make synthesis` sources env.sh and exports TOP + LIB_DB, and\n"
        "# env.sh refuses to run at all when LIB_DB is not in the environment. This file\n"
        "# supplies them to a dc_shell started without the Makefile.\n"
        f'set ::env(TOP)    "{top}"\n'
        'if {![info exists ::env(LIB_DB)] || $::env(LIB_DB) eq ""} {\n'
        f'    set ::env(LIB_DB) "{lib_db}"\n'
        "}\n"
    )
    if lib_db == "FILL_IN_LIB_DB_PATH":
        print(
            "[synthesis bootstrap] wrote scripts/config.tcl "
            "(export LIB_DB before make synthesis)"
        )
    else:
        print(f"[synthesis bootstrap] wrote scripts/config.tcl (LIB_DB={lib_db})")


def run(workdir, top: str | None = None) -> int:
    if not _TEMPLATE_DIR.is_dir():
        _err(f"missing template directory: {_TEMPLATE_DIR}")
        return 1

    # The design tree is the CWD (kernel.py + stage-subagent contract). Resolve a
    # relative workdir against it + drop trailing slash.
    tree_root = Path.cwd()
    dest = Path(workdir)
    if not dest.is_absolute():
        dest = tree_root / dest
    dest = Path(str(dest).rstrip("/"))  # consistent path resolution

    inputs = json.loads((dest / "dispatch.json").read_text(encoding="utf-8"))["inputs"]
    rtl_dir = Path(inputs["rtl"])

    if not top:
        top = top_from_manifest(inputs["manifest"])
    if not top:
        _err("cannot read top-module name; pass --top <name>")
        _err("  Design/specification/manifest.json must carry a 'module' name.")
        return 1

    dest.mkdir(parents=True, exist_ok=True)
    # Every fresh workdir already holds the kernel's dispatch.json; only treat it as
    # already-deployed when a Makefile is present.
    if (dest / "Makefile").is_file():
        _err(f"already deployed (detected {dest / 'Makefile'})")
        _err(
            f"  To redeploy, back up and remove {dest}/"
            "{Makefile,constraints.sdc,scripts/} first."
        )
        return 1

    # carry_self (kernel.py) restores the previous round's constraints.sdc into the fresh
    # workdir before this verb runs, and it holds the timing exceptions and the documented
    # uncertainty/drive values the agent supplemented against real RTL. A carried file wins:
    # re-copying the specification SDC over it would silently throw that work away and
    # re-run synthesis against bare constraints.
    carried_sdc = (dest / "constraints.sdc").is_file()

    # Checked BEFORE the deploy: a failure after copytree would leave the Makefile that the
    # already-deployed guard above then refuses to redeploy over — the workdir would block its
    # own retry. Fail closed rather than fall back to any default constraint set: a run whose
    # clock port matches nothing is unconstrained, and dc_shell then reports a large positive
    # slack — a PASSING PPA verdict from constraints nobody wrote.
    user_sdc = Path(inputs["sdc"]) / "constraints" / f"{top}.sdc"
    if not carried_sdc and not user_sdc.is_file():
        _err(f"SDC source of truth not found: {user_sdc}")
        _err(
            "  specification's derive-constraints writes constraints/<TOP>.sdc; check that "
            "it ran and that --top matches manifest.module."
        )
        return 1

    rtl_load_tcl = _render_rtl_load_tcl(rtl_dir)
    if rtl_load_tcl is None:
        return 1

    shutil.copytree(_TEMPLATE_DIR, dest, dirs_exist_ok=True)

    env_sh = dest / "env.sh"
    if carried_sdc:
        print(
            "[synthesis bootstrap] carried constraints.sdc used "
            "(survived from a prior round)"
        )
    else:
        shutil.copyfile(user_sdc, dest / "constraints.sdc")
        print(
            f"[synthesis bootstrap] using "
            f"Design/specification/constraints/{top}.sdc -> constraints.sdc"
        )
    _sub(env_sh, "MY_TOP", top)

    _sub(dest / "scripts" / "dc_run.tcl", "MY_RTL_DIR", str(rtl_dir))

    (dest / "scripts" / "rtl_load.tcl").write_text(rtl_load_tcl)

    _write_config_tcl(dest, top)

    print(f"\n[synthesis bootstrap] deployed {dest}")
    print(f"  TOP={top}")
    print(f"  RTL_DIR={rtl_dir}")
    return 0
