# SDC constraints for tpu_top
# Generated by the derive-constraints verb from clocks.json + design.md §1.4.1 — do not hand-edit.
# Note: clock periods MUST match tpu_top.sgdc.

create_clock -name i_clk -period 10.0 [get_ports i_clk]

set_clock_uncertainty -setup 0.2 [all_clocks]   ;# placeholder; replace per process library
set_clock_uncertainty -hold  0.0 [all_clocks]   ;# pre-CTS hold = 0; replace per CTS skew

set_input_delay  3.0 -clock i_clk [get_ports {in1}]
set_input_delay  3.0 -clock i_clk [get_ports {in2}]
set_input_delay  3.0 -clock i_clk [get_ports {in1_en}]
set_input_delay  3.0 -clock i_clk [get_ports {in2_en}]
set_input_delay  3.0 -clock i_clk [get_ports {start}]
set_output_delay 3.0 -clock i_clk [get_ports {o_full}]
set_output_delay 3.0 -clock i_clk [get_ports {o_empty}]
set_output_delay 3.0 -clock i_clk [get_ports {done}]
set_input_delay  3.0 -clock i_clk [get_ports {i_paddr}]
set_input_delay  3.0 -clock i_clk [get_ports {i_psel}]
set_input_delay  3.0 -clock i_clk [get_ports {i_pwrite}]
set_input_delay  3.0 -clock i_clk [get_ports {i_pwdata}]
set_input_delay  3.0 -clock i_clk [get_ports {i_penable}]
set_output_delay 3.0 -clock i_clk [get_ports {o_prdata}]
set_output_delay 3.0 -clock i_clk [get_ports {counter}]
