# Auto-generated by the timing bootstrap verb — TOP + LIB_DB injection surface.
# pt_shell sources this; editing LIB_DB here does not require a re-bootstrap.
set TOP    tpu_top
set LIB_DB /home/eda/Foundry/TSMC.90/slow.db
