# Auto-generated by synthesis bootstrap — dc_shell / pt_shell configuration.
# dc_shell does not inherit shell env vars; this file is the sole entry point
# for TOP and LIB_DB. Editing LIB_DB here does not require a re-bootstrap.
set ::env(TOP)    "tpu_top"
set ::env(LIB_DB) "/home/eda/Foundry/TSMC.90/slow.db"
