# ==============================================================================
# dc_run.tcl — Design Compiler synthesis driver.
#
# Invocation (from the Design/synthesis/ workdir, launched by the Makefile):
#   dc_shell -f scripts/dc_run.tcl | tee run.log
#
# Required env vars (provided by env.sh):
#   TOP     Top module name.
#   LIB_DB  Standard-cell library .db path.
# ==============================================================================

# --- Load configuration (fallback when env.sh → dc_shell env handover fails) ---
if {[file exists [file join [file dirname [info script]] config.tcl]]} {
    source [file join [file dirname [info script]] config.tcl]
}

# --- Env-var validation ---
foreach _var {TOP LIB_DB WIRE_LOAD_MODEL} {
    if {![info exists ::env($_var)] || $::env($_var) eq ""} {
        puts stderr "ERROR: environment variable $_var not set (source env.sh)"
        exit 1
    }
}
if {![file isfile $::env(LIB_DB)]} {
    puts stderr "ERROR: LIB_DB is not a regular file: $::env(LIB_DB)"
    exit 1
}

set top    $::env(TOP)
set lib_db $::env(LIB_DB)
set wlm    $::env(WIRE_LOAD_MODEL)

set reports_dir [file join [pwd] reports]
set results_dir [file join [pwd] out]
file mkdir $reports_dir
file mkdir $results_dir

puts "INFO: top         = $top"
puts "INFO: lib_db      = $lib_db"
puts "INFO: wire_load   = $wlm"
puts "INFO: reports_dir = $reports_dir"
puts "INFO: results_dir = $results_dir"

# --- Library configuration ---
set_app_var target_library [list $lib_db]
set_app_var link_library   [list "*" $lib_db]
set_app_var search_path    [concat [list "." "MY_RTL_DIR" [file dirname $lib_db]] \
                                   [get_app_var search_path]]

# --- RTL ingest (analyze + elaborate) ---
# rtl_load.tcl is regenerated by synthesis bootstrap from
# Design/rtl-design/rtl-files.json. It contains analyze invocations in dependency
# order; search_path is configured by the set_app_var line above, and each child's
# incdirs are emitted onto search_path inside rtl_load.tcl.
define_design_lib WORK -path ./work
source [file join [file dirname [info script]] rtl_load.tcl]

# elaborate / link return 0 on failure, and neither failure is caught downstream:
# DC classifies an unresolved reference as a Warning, so the check_design gate below
# never fires on it, and `compile_ultra` succeeds on the reduced design. The result would
# be a netlist missing a whole module, reported as a passing (smaller) QoR. Gate both.
if {![elaborate $top]} {
    puts stderr "ERROR: elaborate failed for $top"
    exit 1
}
current_design $top
if {![link]} {
    puts stderr "ERROR: link failed - unresolved references (a module is missing from the RTL set; see the unresolved-reference warnings above)"
    exit 1
}

set _check_rpt [file join $reports_dir "check_design.rpt"]
check_design > $_check_rpt

# Abort if check_design reported any errors — otherwise compile failure log
# obscures the real upstream cause.
set _fh [open $_check_rpt r]
set _check_content [read $_fh]
close $_fh
if {[regexp -line {^Error:} $_check_content]} {
    puts stderr "ERROR: check_design reported errors - see $_check_rpt"
    exit 1
}

# --- Timing constraints ---
source [file join [pwd] constraints.sdc]

# --- Interconnect estimate ---
# WIRE_LOAD_MODEL names a model the library carries, or `none`. A library declares neither a
# default nor a selection group, so nothing selects one unless this does, and the choice is
# not free either way: measured against a TSMC 90 library, the smallest bucket cost
# OpenTitan's i2c its whole 2.47 ns of setup margin and the largest raised total cell area by
# 18% to 65%. `none` is a legal answer, and what it buys is reports that say so out loud.
# `write_sdc` below emits whichever was chosen, and both PT flows read that SDC, so this is
# the one place it is decided.
if {$wlm ne "none"} {
    set_wire_load_model -name $wlm
}
set_wire_load_mode top

# --- Synthesis ---
# compile_ultra is this flow's mapping command: the PPA targets are judged against its
# QoR, not plain compile's. It needs a DC-Ultra license, which env-precheck smoke-tests
# before the pipeline runs. Return value is 0 on failure, as with elaborate / link.
if {![compile_ultra]} {
    puts stderr "ERROR: compile_ultra failed - design remains unmapped"
    exit 1
}

# --- Reports ---
report_qor                                       > [file join $reports_dir "qor.rpt"]
set _area_rpt [file join $reports_dir "area.rpt"]
report_area   -hierarchy                         > $_area_rpt

# The area report is the only reliable signal of what actually took. `set_wire_load_model`
# returns success for a name the library does not have (it prints `Error: Wire load ... not
# found` without raising) and the design attribute stays unset either way, so neither the
# return value nor the attribute distinguishes the cases. Checked both ways, because a run
# whose reports disagree with what was asked for is not the run that was asked for.
set _fh [open $_area_rpt r]
set _area_content [read $_fh]
close $_fh
set _no_wlm [regexp {No wire load specified} $_area_content]
if {$wlm ne "none" && $_no_wlm} {
    puts stderr "ERROR: wire load model '$wlm' is not in $lib_db (report_lib lists what is)"
    exit 1
}
if {$wlm eq "none" && !$_no_wlm} {
    puts stderr "ERROR: WIRE_LOAD_MODEL=none, but $_area_rpt reports an interconnect estimate"
    exit 1
}
report_timing -max_paths 20 -nworst 1            > [file join $reports_dir "timing_setup.rpt"]
report_timing -delay min -max_paths 20 -nworst 1 > [file join $reports_dir "timing_hold.rpt"]
report_power                                     > [file join $reports_dir "power.rpt"]

# --- Output netlist and constraints ---
change_names -rules verilog -hierarchy

write -format verilog -hierarchy -output [file join $results_dir "${top}_syn.v"]
write_sdc                                [file join $results_dir "${top}_syn.sdc"]
write_sdf -version 3.0                   [file join $results_dir "${top}_syn.sdf"]

puts "INFO: synthesis finished — netlist: out/${top}_syn.v"
quit
