# ==============================================================================
# dc_run.tcl — Design Compiler synthesis driver.
#
# Invocation (from the Design/synthesis/ workdir, launched by the stage CLI):
#   dc_shell -f scripts/dc_run.tcl | tee run.log
#
# Calculation settings (provided by config.tcl):
#   TOP     Top module name.
#   LIB_DB  Standard-cell library .db path.
# ==============================================================================

# --- Calculation settings ---
source [file join [pwd] config.tcl]
foreach _var {TOP LIB_DB WIRE_LOAD_MODEL} {
    if {![info exists $_var] || [set $_var] eq ""} {
        puts stderr "ERROR: setting $_var not set in config.tcl"
        exit 1
    }
}
if {![file isfile $LIB_DB]} {
    puts stderr "ERROR: LIB_DB is not a regular file: $LIB_DB"
    exit 1
}

set top    $TOP
set lib_db $LIB_DB
set wlm    $WIRE_LOAD_MODEL

set reports_dir [file join [pwd] reports]
set results_dir [file join [pwd] out]
file mkdir $reports_dir
file mkdir $results_dir

puts "INFO: top         = $top"
puts "INFO: lib_db      = $lib_db"
puts "INFO: wire_load   = $wlm"
puts "INFO: reports_dir = $reports_dir"
puts "INFO: results_dir = $results_dir"

# --- Library configuration ---
set_app_var target_library [list $lib_db]
set_app_var link_library   [list "*" $lib_db]
set_app_var search_path    [concat [list "." MY_RTL_DIR [file dirname $lib_db]] \
                                   [get_app_var search_path]]

# --- RTL ingest (analyze + elaborate) ---
# rtl_load.tcl is regenerated by synthesis bootstrap from
# Design/rtl-design/rtl-files.json. It contains analyze invocations in dependency
# order; include directories are emitted onto search_path inside rtl_load.tcl.
define_design_lib WORK -path ./work
source [file join [file dirname [info script]] rtl_load.tcl]

# elaborate/link return 0 on failure; unresolved references can appear only as warnings.
if {![elaborate $top]} {
    puts stderr "ERROR: elaborate failed for $top"
    exit 1
}
current_design $top
if {![link]} {
    puts stderr "ERROR: link failed - unresolved references (a module is missing from the RTL set; see the unresolved-reference warnings above)"
    exit 1
}

set _check_rpt [file join $reports_dir "check_design.rpt"]
check_design > $_check_rpt

# Abort if check_design reported any errors — otherwise compile failure log
# obscures the real upstream cause.
set _fh [open $_check_rpt r]
set _check_content [read $_fh]
close $_fh
if {[regexp -line {^Error:} $_check_content]} {
    puts stderr "ERROR: check_design reported errors - see $_check_rpt"
    exit 1
}

# --- Timing constraints ---
source [file join [pwd] constraints.sdc]
source [file join [pwd] constraints.local.sdc]

# --- Interconnect estimate ---
# Apply the selected interconnect estimate; write_sdc carries it downstream.
if {$wlm ne "none"} {
    set_wire_load_model -name $wlm
}
set_wire_load_mode top

# --- Synthesis ---
# The supplied mapping flow uses DC-Ultra. compile_ultra returns 0 on failure.
if {![compile_ultra]} {
    puts stderr "ERROR: compile_ultra failed - design remains unmapped"
    exit 1
}

# --- Reports ---
report_qor                                       > [file join $reports_dir "qor.rpt"]
set _area_rpt [file join $reports_dir "area.rpt"]
report_area   -hierarchy                         > $_area_rpt

# set_wire_load_model can return success for an absent model. Check the effective setting.
set _fh [open $_area_rpt r]
set _area_content [read $_fh]
close $_fh
set _no_wlm [regexp {No wire load specified} $_area_content]
if {$wlm ne "none" && $_no_wlm} {
    puts stderr "ERROR: wire load model '$wlm' is not in $lib_db (report_lib lists what is)"
    exit 1
}
if {$wlm eq "none" && !$_no_wlm} {
    puts stderr "ERROR: WIRE_LOAD_MODEL=none, but $_area_rpt reports an interconnect estimate"
    exit 1
}
redirect [file join $reports_dir "timing_setup.rpt"] {
    report_units
    report_timing -delay max -max_paths 20 -nworst 1 -significant_digits 13
}
redirect [file join $reports_dir "timing_hold.rpt"] {
    report_units
    report_timing -delay min -max_paths 20 -nworst 1 -significant_digits 13
}
report_power                                     > [file join $reports_dir "power.rpt"]

# --- Output netlist and constraints ---
change_names -rules verilog -hierarchy

write -format verilog -hierarchy -output [file join $results_dir "${top}_syn.v"]
write_sdc                                [file join $results_dir "${top}_syn.sdc"]
write_sdf -version 3.0                   [file join $results_dir "${top}_syn.sdf"]

puts "INFO: synthesis finished — netlist: out/${top}_syn.v"
quit
