# ==============================================================================
# dc_run.tcl — Design Compiler synthesis driver.
#
# Invocation (from the Design/synthesis/ workdir, launched by the Makefile):
#   dc_shell -f scripts/dc_run.tcl | tee run.log
#
# Required env vars (provided by env.sh):
#   TOP     Top module name.
#   LIB_DB  Standard-cell library .db path.
# ==============================================================================

# --- Load configuration (fallback when env.sh → dc_shell env handover fails) ---
if {[file exists [file join [file dirname [info script]] config.tcl]]} {
    source [file join [file dirname [info script]] config.tcl]
}

# --- Env-var validation ---
foreach _var {TOP LIB_DB} {
    if {![info exists ::env($_var)] || $::env($_var) eq ""} {
        puts stderr "ERROR: environment variable $_var not set (source env.sh)"
        exit 1
    }
}
if {![file isfile $::env(LIB_DB)]} {
    puts stderr "ERROR: LIB_DB is not a regular file: $::env(LIB_DB)"
    exit 1
}

set top    $::env(TOP)
set lib_db $::env(LIB_DB)

set reports_dir [file join [pwd] reports]
set results_dir [file join [pwd] out]
file mkdir $reports_dir
file mkdir $results_dir

puts "INFO: top         = $top"
puts "INFO: lib_db      = $lib_db"
puts "INFO: reports_dir = $reports_dir"
puts "INFO: results_dir = $results_dir"

# --- Library configuration ---
set_app_var target_library [list $lib_db]
set_app_var link_library   [list "*" $lib_db]
set_app_var search_path    [concat [list "." "MY_RTL_DIR" [file dirname $lib_db]] \
                                   [get_app_var search_path]]

# --- RTL ingest (analyze + elaborate) ---
# rtl_load.tcl is regenerated by synthesis bootstrap from
# Design/rtl-design/rtl-files.json. It contains analyze invocations in dependency
# order; search_path is configured by the set_app_var line above, and each child's
# incdirs are emitted onto search_path inside rtl_load.tcl.
define_design_lib WORK -path ./work
source [file join [file dirname [info script]] rtl_load.tcl]

# elaborate / link return 0 on failure, and neither failure is caught downstream:
# DC classifies an unresolved reference as a Warning, so the check_design gate below
# never fires on it, and `compile` succeeds on the reduced design. The result would be
# a netlist missing a whole module, reported as a passing (smaller) QoR. Gate both.
if {![elaborate $top]} {
    puts stderr "ERROR: elaborate failed for $top"
    exit 1
}
current_design $top
if {![link]} {
    puts stderr "ERROR: link failed — unresolved references (a module is missing from the RTL set; see the unresolved-reference warnings above)"
    exit 1
}

set _check_rpt [file join $reports_dir "check_design.rpt"]
check_design > $_check_rpt

# Abort if check_design reported any errors — otherwise compile failure log
# obscures the real upstream cause.
set _fh [open $_check_rpt r]
set _check_content [read $_fh]
close $_fh
if {[regexp -line {^Error:} $_check_content]} {
    puts stderr "ERROR: check_design reported errors — see $_check_rpt"
    exit 1
}

# --- Timing constraints ---
source [file join [pwd] constraints.sdc]

# --- Synthesis ---
# compile_ultra requires a DC-Ultra license; we use compile and check its
# Tcl return value (0 on failure).
if {![compile]} {
    puts stderr "ERROR: compile failed — design remains unmapped"
    exit 1
}

# --- Reports ---
report_qor                                       > [file join $reports_dir "qor.rpt"]
report_area   -hierarchy                         > [file join $reports_dir "area.rpt"]
report_timing -max_paths 20 -nworst 1            > [file join $reports_dir "timing_setup.rpt"]
report_timing -delay min -max_paths 20 -nworst 1 > [file join $reports_dir "timing_hold.rpt"]
report_power                                     > [file join $reports_dir "power.rpt"]

# --- Output netlist and constraints ---
change_names -rules verilog -hierarchy

write -format verilog -hierarchy -output [file join $results_dir "${top}_syn.v"]
write_sdc                                [file join $results_dir "${top}_syn.sdc"]
write_sdf -version 3.0                   [file join $results_dir "${top}_syn.sdf"]

puts "INFO: synthesis finished — netlist: out/${top}_syn.v"
quit
