# Auto-generated by the timing bootstrap verb from TOP and $LIB_DB — do not hand-edit.
# Promoted with the run: this is the record of which library the STA was linked against.
set TOP    MY_TOP
set LIB_DB FILL_IN_LIB_DB_PATH
