# Auto-generated by bootstrap_timing_analysis.sh — TOP + LIB_DB injection surface.
# pt_shell sources this; editing LIB_DB here does not require a re-bootstrap.
set TOP    MY_TOP
set LIB_DB FILL_IN_LIB_DB_PATH
