# tests/unit/test_rtl_ledger.py
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "skills/rtl-design/scripts"))
from rtl._ledger import LedgerError, load_ledger, merge_filter  # noqa: E402

_ANN = {
    "sgdc": {
        "sync_cell": [],
        "reset_synchronizer": [],
        "set_case_analysis": [],
        "quasi_static": [],
    },
    "sdc": {
        "create_generated_clock": [],
        "set_multicycle_path": [],
        "set_false_path": [],
    },
}


def _rec(files):
    return {"files": files, "annotations": _ANN}


def test_merge_overlays_fresh_onto_seeded():
    seeded = {"a": _rec(["a.sv"]), "b": _rec(["b_old.sv"])}
    fresh = {"b": _rec(["b_new.sv"])}
    out = merge_filter(seeded, fresh, ["a", "b"])
    assert out["b"]["files"] == ["b_new.sv"]  # fresh wins
    assert out["a"]["files"] == ["a.sv"]  # untouched carried forward


def test_merge_emits_manifest_order_not_reap_order():
    # Every downstream filelist is generated by walking these keys, so the key order IS
    # each tool's compile order. It must come from the manifest, not from the order the
    # main thread happened to serialize the reaped reports in, and it must not shift when
    # a later round re-dispatches a subset.
    roster = ["a", "b", "c"]
    reversed_reap = {"c": _rec(["c.sv"]), "b": _rec(["b.sv"]), "a": _rec(["a.sv"])}
    assert list(merge_filter({}, reversed_reap, roster)) == roster
    assert list(merge_filter(reversed_reap, {"b": _rec(["b2.sv"])}, roster)) == roster
    # a child the manifest grew lands at its manifest position, not appended last
    assert (
        list(
            merge_filter(
                {"a": _rec(["a.sv"]), "c": _rec(["c.sv"])},
                {"b": _rec(["b.sv"])},
                roster,
            )
        )
        == roster
    )


def test_merge_filters_removed_child_F2():
    # manifest shrank: 'c' is gone from the roster -> evicted from merged ledger
    seeded = {"a": _rec(["a.sv"]), "c": _rec(["c.sv"])}
    out = merge_filter(seeded, {}, ["a"])
    assert "c" not in out
    assert set(out) == {"a"}


def _write(d, files=None, anns=None):
    import json

    (d / "rtl-files.json").write_text(json.dumps(files if files is not None else {}))
    (d / "constraint-annotations.json").write_text(
        json.dumps(anns if anns is not None else {})
    )
    return d


def test_load_ledger_merges_the_two_sidecars(tmp_path):
    wd = _write(tmp_path, {"a": {"files": ["a.sv"]}}, {"a": _ANN})
    got = load_ledger(wd)
    assert got["a"]["files"] == ["a.sv"]
    assert got["a"]["annotations"] == _ANN


def test_load_ledger_raises_when_a_sidecar_is_absent(tmp_path):
    import json

    (tmp_path / "rtl-files.json").write_text(json.dumps({"a": {"files": ["a.sv"]}}))
    with pytest.raises(LedgerError, match="constraint-annotations.json"):
        load_ledger(tmp_path)


def test_load_ledger_raises_on_roster_disagreement(tmp_path):
    # The two are written together by one verb, so a child in one and not the other is a
    # defect rather than a partial result.
    wd = _write(
        tmp_path, {"a": {"files": ["a.sv"]}, "b": {"files": ["b.sv"]}}, {"a": _ANN}
    )
    with pytest.raises(LedgerError, match="roster"):
        load_ledger(wd)


def test_load_ledger_raises_on_missing_annotation_category(tmp_path):
    # An omitted category and an explicit [] are not the same claim: the child contract
    # requires every category, so the schema does too.
    lean = {"sgdc": {"sync_cell": []}, "sdc": _ANN["sdc"]}
    wd = _write(tmp_path, {"a": {"files": ["a.sv"]}}, {"a": lean})
    with pytest.raises(LedgerError, match="required property"):
        load_ledger(wd)


def test_load_ledger_raises_on_null_annotation_block(tmp_path):
    # M4: null-valued blocks pass a key-only check yet crash _agg downstream.
    wd = _write(
        tmp_path, {"a": {"files": ["a.sv"]}}, {"a": {"sgdc": None, "sdc": None}}
    )
    with pytest.raises(LedgerError, match="not of type 'object'"):
        load_ledger(wd)


def test_load_ledger_raises_on_empty_files_list(tmp_path):
    wd = _write(tmp_path, {"a": {"files": []}}, {"a": _ANN})
    with pytest.raises(LedgerError, match="files"):
        load_ledger(wd)


def test_load_ledger_raises_on_malformed_json(tmp_path):
    wd = _write(tmp_path, {"a": {"files": ["a.sv"]}}, {"a": _ANN})
    (wd / "rtl-files.json").write_text("{not json")
    with pytest.raises(LedgerError):
        load_ledger(wd)


def test_write_ledger_round_trips(tmp_path):
    from rtl._ledger import write_ledger

    ledger = {"a": {"files": ["a.sv"], "incdirs": ["inc"], "annotations": _ANN}}
    write_ledger(tmp_path, ledger)
    assert load_ledger(tmp_path) == ledger
