#!/usr/bin/env python3
"""Preserve authored setup and refresh lint inputs from the current dispatch."""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

# This file: skills/lint-cdc/scripts/lintcdc/bootstrap.py
#   parents[2] = skills/lint-cdc   (-> templates/, ships with the skill)
# The kernel hands this verb an ABSOLUTE workdir, so nothing here depends on where it
# was launched from. A relative --workdir is still resolved against the CWD, for a
# human running the verb by hand from inside the module.
SCRIPT_PATH = Path(__file__).resolve()
TEMPLATE_DIR = SCRIPT_PATH.parents[2] / "templates"

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def report_error(msg: str) -> None:
    print(f"[lintcdc bootstrap] {msg}", file=sys.stderr)


def top_from_manifest(manifest_dir: Path) -> str | None:
    """TOP from the injected manifest's `module` — the name the specification stage
    authored, which every other copy in the tree derives from."""
    f = Path(manifest_dir) / "manifest.json"
    if not f.is_file():
        return None
    try:
        top = json.loads(f.read_text(encoding="utf-8")).get("module")
    except json.JSONDecodeError:
        return None
    return top if isinstance(top, str) and IDENT_RE.match(top) else None


def sync_filelist(dest: Path, rtl_dir: Path) -> int:
    """Generate scripts/filelist.txt from rtl-files.json, anchoring every RTL path at the
    ABSOLUTE injected rtl_dir (no relpath climb). Fail-closed (return 1) when the file is
    missing, unreadable, or lists nothing. Not because the round would otherwise pass — an
    empty sourcelist makes SpyGlass emit `CMD_top ... Fatal: top '<TOP>' : Design unit not
    found`, which the gate counts as an error — but because that message sends the reader
    after a top name that is fine. The cause is upstream and is known here.

    Not validated here: rtl-design schema-validates rtl-files.json when it writes it, and a
    stage does not reach into another skill's references/ (skills stay decoupled).
    """
    src = rtl_dir / "rtl-files.json"
    if not src.is_file():
        report_error(f"{src} not found")
        report_error("  Re-run rtl-design: it authors this sidecar.")
        return 1
    try:
        rtl_files = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        report_error(f"{src} is not valid JSON: {e}")
        return 1
    entries = rtl_files["files"]
    incdirs = rtl_files.get("incdirs", [])
    if not entries:
        report_error(f"{src} lists no RTL files")
        report_error("  Re-run rtl-design: it authors this sidecar.")
        return 1
    header = [
        "# ==============================================================================",
        "# filelist.txt — RTL file list (SpyGlass sourcelist format).",
        "# Generated by the lint-cdc bootstrap verb from Design/rtl-design/rtl-files.json.",
        "# Paths are absolute (re-anchored to the injected rtl-design stage root).",
        "# ==============================================================================",
        "",
        "# Header search paths",
        *[f"+incdir+{rtl_dir}/{d}" for d in incdirs],
        "",
        "# RTL source files (in dependency order)",
    ]
    body = [f"{rtl_dir}/{e}" for e in entries]
    (dest / "scripts" / "filelist.txt").write_text("\n".join(header + body) + "\n")
    print(
        f"  filelist.txt: generated from Design/rtl-design/rtl-files.json ({len(entries)} files)"
    )
    return 0


def deploy_no_clobber(src_root: Path, dest: Path) -> set[str]:
    """Copy every template file into dest UNLESS dest already has one at that path —
    a carried human-audited file (brought forward by kernel.py's carry_self before
    this verb runs) always wins over the pristine template."""
    installed = set()
    for p in src_root.rglob("*"):
        if p.is_dir():
            continue
        d = dest / p.relative_to(src_root)
        if d.exists():
            continue  # carried human-audited file — never overwrite
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, d)
        installed.add(p.relative_to(src_root).as_posix())
    return installed


SGDC_ROW = {
    "sync_cell": "sync_cell -name {}",
    "reset_synchronizer": "reset_synchronizer -name {}",
    "quasi_static": "quasi_static -name {}",
}


def annotation_lines(rtl_dir: Path) -> list[str] | None:
    """The `sgdc` block of every child of constraint-annotations.json, as SGDC lines.

    Generated rather than transcribed by hand. The sidecar carries exact names and the
    mapping to SGDC is fixed, so a human in the middle adds no judgment and subtracts a
    guarantee: a transcriber who quietly corrects a wrong name hides a defect belonging to
    the sidecar's author, which is exactly where this stage's failure routing sends it.
    """
    src = rtl_dir / "constraint-annotations.json"
    if not src.is_file():
        report_error(f"{src} not found")
        report_error("  Re-run rtl-design: it authors this sidecar.")
        return None
    try:
        ann = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        report_error(f"{src} is not valid JSON: {e}")
        return None
    out: list[str] = []
    for child in sorted(ann):
        block = (ann[child] or {}).get("sgdc") or {}
        rows: list[str] = []
        for key, form in SGDC_ROW.items():
            rows += [form.format(v) for v in block.get(key) or []]
        rows += [
            f"set_case_analysis -name {e['port']} -value {e['value']}"
            for e in block.get("set_case_analysis") or []
        ]
        if rows:
            out.append(f"# constraint-annotations.json :: {child}")
            out += rows
            out.append("")
    return out


def assemble_sgdc(dest: Path, seed: Path, rtl_dir: Path) -> int:
    """Write the current specification seed and RTL annotations for SpyGlass.

    The project reads the stage's local.sgdc separately, after this file.
    """
    annotations = annotation_lines(rtl_dir)
    if annotations is None:
        return 1
    body = [
        "# =============================================================================",
        "# constraints.sgdc — GENERATED by the lint-cdc bootstrap verb, every round.",
        "# Do not edit: the next round overwrites it. Yours is scripts/local.sgdc.",
        "# =============================================================================",
        "",
        f"# --- specification: constraints/{seed.name} (verbatim) ---",
        seed.read_text(encoding="utf-8").rstrip("\n"),
        "",
        "# --- rtl-design: constraint-annotations.json (generated) ---",
        *(annotations or ["# no child declared one", ""]),
        "",
    ]
    (dest / "scripts" / "constraints.sgdc").write_text("\n".join(body))
    print(
        f"  constraints.sgdc: assembled from constraints/{seed.name}"
        " + constraint-annotations.json"
    )
    return 0


def run(workdir, top: str | None = None) -> int:
    (Path(workdir) / "result.json").unlink(missing_ok=True)
    if not TEMPLATE_DIR.is_dir():
        report_error(f"missing template directory: {TEMPLATE_DIR}")
        return 1

    # The design tree is the CWD (kernel.py + stage-subagent contract). Resolve a
    # relative workdir against it + drop trailing slash.
    tree_root = Path.cwd()
    dest = Path(workdir)
    if not dest.is_absolute():
        dest = tree_root / dest
    dest = Path(str(dest).rstrip("/"))

    # The rtl-design stage root is injected into dispatch.json (dispatch-time), not
    # self-navigated via <module>/Design/rtl-design.
    inputs = json.loads((dest / "dispatch.json").read_text(encoding="utf-8"))["inputs"]
    rtl_dir = Path(inputs["rtl"])

    # Resolve TOP BEFORE mkdir/guard (shell order).
    if not top:
        top = top_from_manifest(inputs["manifest"])
    if not top:
        report_error("cannot read top-module name; pass --top <name>")
        report_error("  Design/specification/manifest.json must carry a 'module' name.")
        return 1

    dest.mkdir(parents=True, exist_ok=True)
    # The seed is a declared input, so its absence is a broken upstream, not a case to
    # fall back from: SpyGlass reading a design with no clock declared reports a clean run.
    seed = Path(inputs["sgdc_seed"]) / "constraints" / f"{top}.sgdc"
    if not seed.is_file():
        report_error(f"SGDC source of truth not found: {seed}")
        report_error(
            "  specification's derive-constraints writes constraints/<TOP>.sgdc; check that "
            "it ran and that --top matches manifest.module."
        )
        return 1

    installed = deploy_no_clobber(TEMPLATE_DIR, dest)
    for rel in (
        "env.sh",
        "scripts/spyglass_lint.prj",
        "scripts/waiver.tcl",
        "scripts/local.sgdc",
    ):
        if rel in installed:
            setup_file = dest / rel
            setup_file.write_text(setup_file.read_text().replace("MY_TOP", top))

    if assemble_sgdc(dest, seed, rtl_dir) != 0:
        return 1

    for sh in (dest / "scripts").glob("*.sh"):
        sh.chmod(sh.stat().st_mode | 0o111)

    exit_code = sync_filelist(dest, rtl_dir)
    if exit_code != 0:
        return exit_code

    print(f"[lintcdc bootstrap] deployed {dest}")
    print(f"  TOP={top}")
    print(
        "  Authored setup is preserved; filelist.txt and constraints.sgdc are regenerated."
    )
    print(
        f'  Next: cd "{dest}" && make all   (requires SpyGlass; -shell -tcl mode does not need Xvfb)'
    )
    return 0
