#!/usr/bin/env python3
"""lintcdc bootstrap — deploy the lint-cdc templates into a run workdir.

Upstream locations (rtl-design, the specification SGDC seed) come from the injected
`<workdir>/dispatch.json` `inputs` table ("rtl" / "sgdc_seed"), never by
self-navigating <module>/Design/.... str.replace does the `sed -i`
work: it has no delimiter hazard.

The deploy is NO-CLOBBER, so a dest file already present when this verb runs — the
previous round's constraints.sgdc / waiver.tcl, restored into the fresh workdir
before it starts — always wins over the pristine template. A genuinely first run
has neither, and seeds constraints.sgdc from the specification stage's
constraints/<TOP>.sgdc instead.

Fail-closed on a missing template dir, an un-inferrable top, an already-deployed
workdir, or an rtl-design file layout that yields no RTL.

Exit codes (returned as int; __main__ does sys.exit):
  0  deployed
  1  fail-closed guard (stderr names which one)
  (2 = usage is owned by argparse in __main__.py)
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

# This file: skills/lint-cdc/scripts/lintcdc/bootstrap.py
#   parents[2] = skills/lint-cdc   (-> templates/, ships with the skill)
# The kernel hands this verb an ABSOLUTE workdir, so nothing here depends on where it
# was launched from. A relative --workdir is still resolved against the CWD, for a
# human running the verb by hand from inside the module.
_HERE = Path(__file__).resolve()
_TEMPLATE_DIR = _HERE.parents[2] / "templates"

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _err(msg: str) -> None:
    print(f"[lintcdc bootstrap] {msg}", file=sys.stderr)


def top_from_manifest(manifest_dir: Path) -> str | None:
    """TOP from the injected manifest's `module` — the name the specification stage
    authored, which every other copy in the tree derives from."""
    f = Path(manifest_dir) / "manifest.json"
    if not f.is_file():
        return None
    try:
        top = json.loads(f.read_text(encoding="utf-8")).get("module")
    except json.JSONDecodeError:
        return None
    return top if isinstance(top, str) and _IDENT_RE.match(top) else None


def _sub(path: Path, placeholder: str, value: str) -> None:
    """In-place placeholder substitution (str.replace — no sed-delimiter hazard)."""
    path.write_text(path.read_text().replace(placeholder, value))


def _sync_filelist(dest: Path, rtl_dir: Path) -> int:
    """Generate scripts/filelist.txt from rtl-files.json, anchoring every RTL path at the
    ABSOLUTE injected rtl_dir (no relpath climb). Fail-closed (return 1) when the file is
    missing, unreadable, or lists nothing: SpyGlass reading an empty sourcelist reports a
    clean run, so a silent no-op here would promote a pass that analyzed no RTL.

    Not validated here: rtl-design schema-validates rtl-files.json when it writes it, and a
    stage does not reach into another skill's references/ (skills stay decoupled).
    """
    src = rtl_dir / "rtl-files.json"
    if not src.is_file():
        _err(f"{src} not found")
        _err("  Re-run rtl-design: it authors this sidecar.")
        return 1
    try:
        rtl_files = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        _err(f"{src} is not valid JSON: {e}")
        return 1
    entries: list[str] = []
    incdirs: list[str] = []
    for name in sorted(rtl_files):
        rec = rtl_files[name]
        for d in rec.get("incdirs") or []:
            if d not in incdirs:
                incdirs.append(d)
        for f in rec.get("files") or []:
            if f not in entries:
                entries.append(f)
    if not entries:
        _err(f"{src} lists no RTL files")
        _err("  Re-run rtl-design: it authors this sidecar.")
        return 1
    header = [
        "# ==============================================================================",
        "# filelist.txt — RTL file list (SpyGlass sourcelist format).",
        "# Generated by the lint-cdc bootstrap verb from Design/rtl-design/rtl-files.json.",
        "# Paths are absolute (re-anchored to the injected rtl-design stage root).",
        "# ==============================================================================",
        "",
        "# Header search paths",
        *([f"+incdir+{rtl_dir}"] + [f"+incdir+{rtl_dir}/{d}" for d in incdirs]),
        "",
        "# RTL source files (in dependency order)",
    ]
    body = [f"{rtl_dir}/{e}" for e in entries]
    (dest / "scripts" / "filelist.txt").write_text("\n".join(header + body) + "\n")
    print(
        f"  filelist.txt: generated from Design/rtl-design/rtl-files.json ({len(entries)} files)"
    )
    return 0


def _deploy_no_clobber(src_root: Path, dest: Path) -> None:
    """Copy every template file into dest UNLESS dest already has one at that path —
    a carried human-audited file (brought forward by kernel.py's carry_self before
    this verb runs) always wins over the pristine template."""
    for p in src_root.rglob("*"):
        if p.is_dir():
            continue
        d = dest / p.relative_to(src_root)
        if d.exists():
            continue  # carried human-audited file — never overwrite
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, d)


def _warn_seed_changed(dest: Path, cold: Path, top: str) -> None:
    """Say so when this round was scheduled BECAUSE the specification SGDC changed.

    The carried constraints.sgdc wins over the seed, which is right — it holds the depth
    annotations and waivable structure a round put there. But the seed's clock/reset block
    is specification's, and once round 1 cold-started from it nothing re-reads it, so a
    correction upstream would land in a file this stage never opens again. The kernel
    already knows: it re-dispatched because that input's fingerprint moved, and names the
    file in dispatch.json's `scope`. Reading `scope` is what makes this fire only then,
    instead of on every rework (the two files always differ after round 1)."""
    try:
        scope = json.loads((dest / "dispatch.json").read_text(encoding="utf-8")).get(
            "scope"
        )
    except (OSError, json.JSONDecodeError):
        return
    tail = f"constraints/{top}.sgdc"
    if not scope or not any(str(p).endswith(tail) for p in scope):
        return
    _err(
        f"the specification SGDC changed this round — dispatch.json scope names {tail}"
    )
    _err(
        "  The carried scripts/constraints.sgdc still holds the OLD clock/reset block. "
        "Reconcile it against"
    )
    _err(f"  {cold} before running, keeping your annotations and waivers.")


def run(workdir, top: str | None = None) -> int:
    if not _TEMPLATE_DIR.is_dir():
        _err(f"missing template directory: {_TEMPLATE_DIR}")
        return 1

    # The design tree is the CWD (kernel.py + stage-subagent contract). Resolve a
    # relative workdir against it + drop trailing slash.
    tree_root = Path.cwd()
    dest = Path(workdir)
    if not dest.is_absolute():
        dest = tree_root / dest
    dest = Path(str(dest).rstrip("/"))

    # The rtl-design stage root is injected into dispatch.json (dispatch-time), not
    # self-navigated via <module>/Design/rtl-design.
    inputs = json.loads((dest / "dispatch.json").read_text(encoding="utf-8"))["inputs"]
    rtl_dir = Path(inputs["rtl"])

    # Resolve TOP BEFORE mkdir/guard (shell order).
    if not top:
        top = top_from_manifest(inputs["manifest"])
    if not top:
        _err("cannot read top-module name; pass --top <name>")
        _err("  Design/specification/manifest.json must carry a 'module' name.")
        return 1

    dest.mkdir(parents=True, exist_ok=True)
    # Every fresh workdir already holds the kernel's dispatch.json; only treat it as
    # already-deployed when a Makefile is present.
    if (dest / "Makefile").is_file():
        _err(f"already deployed (detected {dest / 'Makefile'})")
        _err(
            f"  To redeploy, back up and remove {dest}/{{Makefile,env.sh,scripts/}} first."
        )
        return 1

    # Carried-file check MUST happen BEFORE the no-clobber deploy — once the template
    # is deployed at these paths they become indistinguishable from a genuinely
    # carried file.
    carried_sgdc = (dest / "scripts" / "constraints.sgdc").is_file()
    carried_waiver = (dest / "scripts" / "waiver.tcl").is_file()

    _deploy_no_clobber(_TEMPLATE_DIR, dest)

    # SGDC seed: carried -> cold -> template priority. carry_self (kernel.py) already
    # restores the canonical constraints.sgdc verbatim into the fresh workdir when one
    # exists (already bound to a concrete top -> NOT MY_TOP-substituted); the cold
    # branch seeds a genuinely first run from the injected specification stage root.
    # The template branch keeps the no-clobber-deployed template constraints.sgdc and
    # DOES substitute it.
    sgdc = dest / "scripts" / "constraints.sgdc"
    cold = Path(inputs["sgdc_seed"]) / "constraints" / f"{top}.sgdc"
    sub_targets = [
        "env.sh",
        "scripts/spyglass_lint.prj",
    ]
    if carried_sgdc:
        print(
            "[lintcdc bootstrap] carried scripts/constraints.sgdc used (survived from a prior round)"
        )
        sgdc_source = "scripts/constraints.sgdc (carried)"
        _warn_seed_changed(dest, cold, top)
    elif cold.is_file():
        shutil.copyfile(cold, sgdc)
        print(
            f"[lintcdc bootstrap] cold-start used Design/specification/constraints/{top}.sgdc -> scripts/constraints.sgdc"
        )
        sgdc_source = f"Design/specification/constraints/{top}.sgdc (cold)"
    else:
        sub_targets.append("scripts/constraints.sgdc")  # template copy needs MY_TOP
        sgdc_source = ""
    # Waiver: carried -> template. The canonical waiver.tcl holds accepted waivers, each
    # with the rationale finalize requires, so the no-clobber deploy leaves a carried one
    # untouched; only a fresh template stub needs MY_TOP.
    if not carried_waiver:
        sub_targets.append("scripts/waiver.tcl")
    for rel in sub_targets:
        _sub(dest / rel, "MY_TOP", top)

    # Make the deployed shell scripts executable (best-effort).
    for sh in (dest / "scripts").glob("*.sh"):
        try:
            sh.chmod(sh.stat().st_mode | 0o111)
        except OSError:
            pass

    rc = _sync_filelist(dest, rtl_dir)
    if rc != 0:
        return rc

    print(f"[lintcdc bootstrap] deployed {dest}")
    print(f"  TOP={top}")
    if sgdc_source:
        print(
            f"  clock/reset constraints: synced from {sgdc_source}; add abstract_port associations as needed."
        )
    else:
        print(
            "  clock/reset constraints: edit scripts/constraints.sgdc (clock / reset / abstract_port)."
        )
    print(
        f'  Next: cd "{dest}" && make all   (requires SpyGlass; -shell -tcl mode does not need Xvfb)'
    )
    return 0
