#!/usr/bin/env python3
"""Install VeriPower's native Codex approval rules and dedicated launch profile."""

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "# Generated by VeriPower's Codex adapter.\n"
PROFILE = (
    HEADER
    + 'approval_policy = "on-request"\n'
    + 'approvals_reviewer = "user"\n'
    + 'sandbox_mode = "workspace-write"\n'
    + "\n[features]\nhooks = true\nmulti_agent = true\n"
)


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))


def rules_text(root: Path = ROOT) -> str:
    # An exact argv prefix: other Python commands keep their existing policy.
    kernel = str(root / "framework/scripts/kernel.py")
    return HEADER + "".join(
        "prefix_rule(\n"
        f"    pattern = {json.dumps(['python3', kernel, verb])},\n"
        '    decision = "prompt",\n'
        f"    justification = {json.dumps(reason(verb))},\n"
        ")\n"
        for verb in ("pin", "reopen", "signoff")
    )


def reason(verb: str) -> str:
    # Share the measured wording with the existing harness, without changing it.
    sys.path.insert(0, str(ROOT / "hooks"))
    from ask_judgment_verbs import REASON

    return REASON.format(verb=verb)


def install(home: Path) -> None:
    files = {
        home / "rules/veripower.rules": rules_text(),
        home / "veripower.config.toml": PROFILE,
    }
    # Check both before writing either. Never replace an unrelated user profile.
    for path in files:
        if path.exists() and not path.read_text().startswith(HEADER):
            raise ValueError(f"{path} already exists and is not managed by VeriPower")
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=codex_home(),
        help="Codex configuration directory",
    )
    args = parser.parse_args()
    try:
        install(args.codex_home)
    except (OSError, ValueError) as exc:
        sys.exit(f"veripower-codex: {exc}")
    print("Installed VeriPower approval rules and the veripower profile.")
    print("Start a NEW session with: codex --profile veripower")
    print("Review and enable this plugin's hooks in /hooks before running the flow.")


if __name__ == "__main__":
    main()
    sys.exit(0)
