#!/usr/bin/env python3
"""Install VeriPower's native Codex approval rules and dedicated launch profile."""

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "hooks"))
from ask_judgment_verbs import GATED, REASON  # noqa: E402

HEADER = "# Generated by VeriPower's Codex adapter.\n"
PROFILE = (
    HEADER
    + 'approval_policy = "on-request"\n'
    + 'approvals_reviewer = "user"\n'
    + 'sandbox_mode = "workspace-write"\n'
    + "\n[features]\nhooks = true\nmulti_agent = true\n"
)


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))


def rules_text(root: Path = ROOT) -> str:
    # The absolute path and the spelling used by the shared design-flow skill.
    kernels = [
        str(root / "framework/scripts/kernel.py"),
        str(root / "skills/design-flow/../../framework/scripts/kernel.py"),
    ]
    return HEADER + "".join(
        "prefix_rule(\n"
        f"    pattern = {json.dumps(['python3', kernels, verb])},\n"
        '    decision = "prompt",\n'
        f"    justification = {json.dumps(REASON.format(verb=verb), ensure_ascii=False)},\n"
        ")\n"
        for verb in GATED
    )


def install(home: Path) -> None:
    files = {
        home / "rules/veripower.rules": rules_text(),
        home / "veripower.config.toml": PROFILE,
    }
    # Check both before writing either. Never replace an unrelated user profile.
    for path in files:
        if path.exists() and not path.read_text().startswith(HEADER):
            raise ValueError(f"{path} already exists and is not managed by VeriPower")
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    try:
        install(codex_home())
    except (OSError, ValueError) as exc:
        sys.exit(f"veripower-codex: {exc}")
    print("Installed VeriPower approval rules and the veripower profile.")
    print("Start a NEW session with: codex --profile veripower")
    print("Review and enable this plugin's hooks in /hooks before running the flow.")


if __name__ == "__main__":
    main()
