#!/usr/bin/env python3
"""sim rtl-filelist: generate the workdir's rtl_filelist.f from rtl-files.json.

The RTL file layout is authored upstream as JSON, so this generates the VCS filelist rather
than rewriting a text one. Paths are anchored at the absolute rtl-design stage root injected
via dispatch.json, not a relpath climb, and `+incdir+` is written here and nowhere else.
Private to the bootstrap verb."""

from __future__ import annotations

import json
from pathlib import Path


def load_rtl_files(rtl_root) -> dict:
    """rtl-files.json from the injected rtl-design stage root. Not validated here, for the
    reason given in sim._plan."""
    path = Path(rtl_root) / "rtl-files.json"
    return json.loads(path.read_text(encoding="utf-8"))


def write_rtl_filelist(rtl_files: dict, dst, rtl_root: str) -> None:
    """One `+incdir+` line per include dir, then one path per RTL file.

    Children are emitted in name order and files in their declared order within a child, so
    the compile order is deterministic.
    """
    incdirs: list[str] = []
    files: list[str] = []
    for name in sorted(rtl_files):
        rec = rtl_files[name]
        for d in rec.get("incdirs") or []:
            entry = d if d.startswith(("/", "$")) else f"{rtl_root}/{d}"
            if entry not in incdirs:
                incdirs.append(entry)
        for f in rec["files"]:
            entry = f if f.startswith(("/", "$")) else f"{rtl_root}/{f}"
            if entry not in files:
                files.append(entry)
    lines = [
        "// rtl_filelist.f — generated by the sim bootstrap verb from rtl-files.json.",
        "// Do not hand-edit; re-run bootstrap.",
    ]
    lines += [f"+incdir+{d}" for d in incdirs]
    lines += files
    Path(dst).write_text("\n".join(lines) + "\n", encoding="utf-8")
