#!/usr/bin/env python3
"""sim rtl-filelist: generate the workdir's rtl_filelist.f from rtl-files.json.

The RTL file layout is authored upstream as JSON, so this generates the VCS filelist rather
than rewriting a text one. Paths are anchored at the absolute rtl-design stage root injected
via dispatch.json, not a relpath climb, and `+incdir+` is written here and nowhere else.
Private to the bootstrap verb."""

from __future__ import annotations

import json
from pathlib import Path


def load_rtl_files(rtl_root) -> dict:
    """rtl-files.json from the injected rtl-design stage root. Indexed, not checked for
    existence: it is a declared input of this rule, and the kernel refuses to dispatch until
    rtl-design's latest outcome has recorded it with a fingerprint matching disk (a deleted
    file fingerprints as `unknown`, which never matches). Not validated either, for the reason
    given in sim._plan."""
    path = Path(rtl_root) / "rtl-files.json"
    return json.loads(path.read_text(encoding="utf-8"))


def write_rtl_filelist(rtl_files: dict, dst, rtl_root: str) -> None:
    """Preserve global source and include order; append simulation-only DPI sources."""

    def anchored(path):
        return path if path.startswith(("/", "$")) else f"{rtl_root}/{path}"

    lines = [
        "// rtl_filelist.f — generated by sim bootstrap from rtl-files.json.",
        "// Do not hand-edit; re-run bootstrap.",
    ]
    lines += [f"+incdir+{anchored(d)}" for d in rtl_files.get("incdirs", [])]
    lines += [anchored(f) for f in rtl_files["files"] + rtl_files.get("sim_only", [])]
    Path(dst).write_text("\n".join(lines) + "\n", encoding="utf-8")
